version: '3.7'
services:
  ui:
    build: ./adulting-front-end
    ports:
      - '80:80'
    depends_on:
      - api
  api:
    build: ./back-end
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
